#!/bin/bash
# Quick Installation Commands - Copy and paste these into your terminal
# Run from: /Users/srinivasmagidewar/My_Docs/ai_projects/ai-moderator-agent

echo "================================================"
echo "AI Moderator Agent - Quick Install Commands"
echo "================================================"
echo ""
echo "Copy and run these commands in your Terminal:"
echo ""
echo "# Step 1: Install Homebrew"
echo "/bin/bash -c \"\$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)\""
echo ""
echo "# Step 2: Add Homebrew to PATH (Apple Silicon)"
echo "echo 'eval \"\$(/opt/homebrew/bin/brew shellenv)\"' >> ~/.zprofile"
echo "eval \"\$(/opt/homebrew/bin/brew shellenv)\""
echo ""
echo "# Step 3: Install system dependencies"
echo "brew install pkg-config ffmpeg livekit-cli"
echo ""
echo "# Step 4: Authenticate with LiveKit"
echo "lk cloud auth"
echo ""
echo "# Step 5: Activate Python environment"
echo "cd /Users/srinivasmagidewar/My_Docs/ai_projects/ai-moderator-agent"
echo "source ai_moderator_agent/bin/activate"
echo ""
echo "# Step 6: Install Python packages"
echo "pip install -r requirements.txt"
echo ""
echo "# Step 7: Download models"
echo "python agent.py download-files"
echo ""
echo "# Step 8: Test setup"
echo "python verify_setup.py"
echo "python scripts/test_connection.py"
echo ""
echo "# Step 9: Run agent!"
echo "python agent.py dev"
echo ""
echo "================================================"
